version: '3.7'
services:
  blueboard-api:
    restart: always
    build:
      context: ../src/.
      dockerfile: BlueBoard.API/Dockerfile
    depends_on:
      - blueboard-db
    ports: 
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  blueboard-db:
    image: 'postgres:latest'
    ports: 
      - 5432:5432
    volumes:
      - blueboard-data:/var/lib/postgresql/data
    env_file:
      - ../src/BlueBoard.API/debug.env

volumes:
  blueboard-data:
    driver: local